Options:
  HideEnableMessage: false
  UpdateChecker: true
  UpdateNotify: true
  DetectInvisPotion: false
  SuperVanish: false
  EventTrails: true
  HideInCombat: false
  BannedWorlds:
    Enable: false
    Worlds:
    - World1
  HideOnMove:
    Enable: false
    Particles: false
    Rains: false
    Event: false
    Wings: false
  SelectSounds:
    Enable: false
    Particles: NOTE_PLING
    Blocks: NOTE_PLING
    Rains: NOTE_PLING
    Wings: NOTE_PLING
    Event: NOTE_PLING
  SimpleFairiyAI: true
  LanguagesMenu: true
  DefaultMode: 0
  PermissionChecker:
    TimerChecker: false
    JoinChecker: false
  BroadcastEventMessages: true
MYSQL:
  Enable: false
  ip: ''
  port: ''
  database: ''
  login: ''
  password: ''
ParticleTrails:
  Heart:
    Slot: 10
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Angry:
    Slot: 11
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Magic:
    Slot: 12
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Fun:
    Slot: 13
    Speed: 1
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Cloud:
    Slot: 14
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Witch:
    Slot: 15
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Ender:
    Slot: 16
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Green:
    Slot: 17
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Spark:
    Slot: 18
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Flame:
    Slot: 19
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  White:
    Slot: 20
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Note:
    Slot: 21
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Snow:
    Slot: 22
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Water:
    Slot: 23
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Lava:
    Slot: 24
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Crit:
    Slot: 25
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Smoke:
    Slot: 26
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Spell:
    Slot: 27
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Enchant:
    Slot: 28
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Splash:
    Slot: 29
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Slime:
    Slot: 30
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Snowball:
    Slot: 31
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Void:
    Slot: 32
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  LavaPop:
    Slot: 33
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Breath:
    Slot: 34
    Speed: 0.1
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Damage:
    Slot: 35
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  EndRod:
    Slot: 36
    Speed: 0
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
  Totem:
    Slot: 37
    Speed: 0.1
    Y: 0
    Amount: 4
    OffsetX: 1
    OffsetY: 1
    OffsetZ: 1
BlockTrails:
  '1':
    Version: S18
    Item: '95:0'
    ItemNew: WHITE_GLASS
    Set: 35,14,35,4,35,5,35,3
    Slot: 10
  '2':
    Version: S18
    Item: '95:1'
    ItemNew: ORANGE_GLASS
    Set: 95,0,95,1,95,2,95,3
    Slot: 11
  '3':
    Version: S18
    Item: '95:2'
    ItemNew: MAGENTA_GLASS
    Set: 153,0,112,0,87,0,89,0
    Slot: 12
  '4':
    Version: S18
    Item: '95:3'
    ItemNew: LIGHT_BLUE_GLASS
    Set: 159,1,159,2,159,8,159,6
    Slot: 13
  '5':
    Version: S18
    Item: '95:4'
    ItemNew: YELLOW_GLASS
    Set: 21,0,129,0,73,0,16,0
    Slot: 14
  '6':
    Version: S18
    Item: '95:5'
    ItemNew: LIME_GLASS
    Set: 46,0,33,0,25,0,152,0
    Slot: 19
  '7':
    Version: S18
    Item: '95:6'
    ItemNew: PINK_GLASS
    Set: 3,2,2,0,13,0,12,0
    Slot: 20
  '8':
    Version: S18
    Item: '95:7'
    ItemNew: SILVER_GLASS
    Set: 42,0,41,0,57,0,133,0
    Slot: 21
Wings:
  Angel:
    File: wing.png
    Slot: 20
    Item: '288:0'
WingsPatterns:
  Pattern1:
    File: pattern.png
    Slot: 1
    Item: '160:10'
