# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    survival112: -1
    survival112_nether: -1
    survival112_the_end: -1
    broville: -1
    ooo: -1
    sparkour: -1
    dreamworld: -1
    mainmenu: -1
    speedforce: -1
    titanstower: -1
    fortressofsolitude: -1
    helicarrier: -1
    infiniteparkour: -1
    chicago: -1
    gotham: -1
    starlabs: -1
    buildworld: -1
    greenfield: -1
    waynemanor: -1
    hallofjustice: -1
    pokemon: -1
    metropolis: -1
    jail: -1
    arcade: -1
    hogwarts: -1
    thephantomzone: -1
    nyc: -1
    infinitycity: -1
    soulstone: -1
  Claims:
    Mode:
      pokemon: Disabled
      survival112: Survival
      metropolis: Disabled
      buildworld: Survival
      sparkour: Survival
      hogwarts: Disabled
      broville: Disabled
      gotham: Disabled
      titanstower: Disabled
      infiniteparkour: Disabled
      soulstone: Disabled
      ooo: Disabled
      survival112_the_end: Survival
      survival112_nether: Survival
      greenfield: Disabled
      nyc: Disabled
      helicarrier: Disabled
      chicago: Disabled
      starlabs: Disabled
      hallofjustice: Disabled
      infinitycity: Disabled
      waynemanor: Disabled
      thephantomzone: Disabled
      dreamworld: Survival
      arcade: Disabled
      speedforce: Disabled
      jail: Disabled
      mainmenu: Disabled
      fortressofsolitude: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 99999
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      survival112: true
      survival112_nether: true
      survival112_the_end: true
      broville: true
      ooo: true
      sparkour: true
      dreamworld: true
      mainmenu: true
      speedforce: true
      titanstower: true
      fortressofsolitude: true
      helicarrier: true
      infiniteparkour: true
      chicago: true
      gotham: true
      starlabs: true
      buildworld: true
      greenfield: true
      waynemanor: true
      hallofjustice: true
      pokemon: true
      metropolis: true
      jail: true
      arcade: true
      hogwarts: true
      thephantomzone: true
      nyc: true
      infinitycity: true
      soulstone: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 99
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust: []
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Advanced:
    fixNegativeClaimblockAmounts: true
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
